---
- hosts: findartifactweb
  become: yes
  vars:
    version: 1.1.0-SNAPSHOT
    appuser: ???
    approot: ???
    appserver: ???
    nginx: ???
    nginxlogdir: ???
  vars_files:
    - vars.yml

  tasks:

    - name: create application directory
      file: path={{ approot }}/log state=directory owner={{ appuser }} group={{ appuser }} mode=0755

    - name: copy nginx config
      template: src=nginx.conf.template dest=/usr/local/nginx/conf/findartifact.conf owner=root group=root mode=0644
      notify:
        - restart nginx

    - name: add nginx config
      lineinfile: dest=/usr/local/nginx/conf/nginx.conf line="include findartifact.conf;" insertafter="^#insertserversbelow" backup=yes
      notify:
        - restart nginx

    - name: copy ring uberjar
      copy: src=target/findartifact-{{ version }}-standalone.jar dest={{ approot }}/find-artifact.jar owner={{ appuser }} group={{ appuser }} mode=0644
      notify:
        - stop application
        - start application

  handlers:

    - name: stop application
      become_user: "{{ appuser }}"
      command: /usr/bin/killall java -u "{{ appuser | quote }}"

    - name: start application
      become_user: "{{ appuser }}"
      shell: java -jar {{ approot }}/find-artifact.jar >> {{ approot }}/log/find-artifact.log 2>&1 & disown
      async: 1
      poll: 0

    - name: restart nginx
      command: "{{ nginx }} -s reload"
